services:
  - type: web
    name: chatgpt-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main.py  # ← Update this if your entrypoint is different
    envVars:
      - key: PORT
        value: 10000
